[package]
name = "resvg-core"
version = "0.1.0"
edition = "2021"

[dependencies]
resvg = "0.45"
usvg = "0.45"
tiny-skia = "0.11"
uniffi = "0.29"
thiserror = "2.0"
fontdb = "0.23"

[lib]
crate-type = ["cdylib", "staticlib"]
path = "src/libs.rs"
